#!/usr/bin/env bash
# Install nginx web server

sudo apt-get update
sudo apt-get -y install nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/hello.html
sudo echo "Hello World!" > /etc/nginx/html/index.html
sudo echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root   /etc/nginx/html;
	index  index.html;
}
" > /etc/nginx/sites-available/default

sudo service nginx restart
