#!/usr/bin/env bash
# custom 404 page that contains the string Ceci n'est pas une page

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow "Nginx HTTP"
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

service nginx restart
