#!/usr/bin/env bash
#Configure HAproxy so that it send traffic to web-01 and web-02
sudo apt -y update
sudo apt -y install haproxy
sudo echo "
frontend http_front
    bind *:80
    default_backend http_back
backend http_back
    balance roundrobin
    server 171478-web-01 18.204.16.158:80 check
    server 171478-web-02 54.237.117.152:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
