#!/usr/bin/env bash
#Fix this container so that Nginx is running as the nginx user.
pkill apache2
sed -i '1c\user nginx;' /etc/nginx/nginx.conf
chmod 644  /etc/nginx/nginx.conf
sed -i 's/^ *listen .*$/listen 8080;/' /etc/nginx/sites-available/default
sudo service nginx restart
